name: Cargo CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_and_lint:
    name: "Cargo: Build & Test & Lint"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo clippy --verbose -- -D clippy::all -D clippy::pedantic -W clippy::nursery -W clippy::missing_errors_doc
